CREATE TABLE COMMENTARY
(
    WRITE_NO NUMBER PRIMARY KEY,
    MEM_NO NUMBER,
    BOOK_NO NUMBER,
    CONTENT VARCHAR2(3000) CONSTRAINT COMMENTARY_CONTENT_NN CHECK (CONTENT IS NOT NULL),
    RATING NUMBER DEFAULT 1 CONSTRAINT COMMENTARY_RATING_NN CHECK (RATING IS NOT NULL),
    WRITE_DATE DATE DEFAULT SYSDATE,

    CONSTRAINT COMMENTARY_MEM_NO_FK FOREIGN KEY(MEM_NO)
    REFERENCES MEMBER(MEM_NO) ON DELETE CASCADE,

    CONSTRAINT COMMENTARY_BOOK_NO_FK FOREIGN KEY(BOOK_NO)
    REFERENCES BOOK(BOOK_NO) ON DELETE CASCADE
);
    
    COMMENT ON COLUMN COMMENTARY.WRITE_NO IS '감상문 번호';
    COMMENT ON COLUMN COMMENTARY.MEM_NO IS '회원번호';
    COMMENT ON COLUMN COMMENTARY.BOOK_NO IS '책번호';
    COMMENT ON COLUMN COMMENTARY.CONTENT IS '감상문 내용';
    COMMENT ON COLUMN COMMENTARY.RATING IS '평점';
    COMMENT ON COLUMN COMMENTARY.WRITE_DATE IS '작성날짜';
    
CREATE SEQUENCE COMMENTARY_SEQ
                INCREMENT BY    1 
                START WITH      1
                MINVALUE        1
                MAXVALUE        99999
                NOCYCLE
                NOCACHE
                NOORDER;
INSERT INTO COMMENTARY(
                WRITE_NO,
                MEM_NO ,
                BOOK_NO,
                CONTENT,
                RATING,
                WRITE_DATE)
            VALUES(COMMENTARY_SEQ.NEXTVAL
                    , 11
                    , 7
                    , 88
                    , '직접 해보는건 어떨까요? 핑퐁이세요?'
                    , 4
                    , SYSDATE
                    ); 