DROP TABLE BOOK;
DROP TABLE GENRE;

CREATE TABLE GENRE(
    G_CODE VARCHAR2(100) CONSTRAINT G_CODE_PK PRIMARY KEY,
    G_NAME VARCHAR2(60) NOT NULL
); 

COMMENT ON COLUMN GENRE.G_CODE IS '장르 CODE';
COMMENT ON COLUMN GENRE.G_NAME IS '장르명';

