DROP TABLE LIKES;

CREATE TABLE LIKES(
    MEM_NO NUMBER REFERENCES MEMBER ON DELETE CASCADE,
    BOOK_NO NUMBER REFERENCES BOOK ON DELETE CASCADE,
    
    CONSTRAINT MEM_BOOK_NO_PFK PRIMARY KEY(MEM_NO, BOOK_NO)
);

COMMENT ON COLUMN LIKES.MEM_NO IS '사용자 번호';
COMMENT ON COLUMN LIKES.BOOK_NO IS '책 번호';


