DROP TABLE MEM_GIS;
CREATE TABLE MEM_GIS(
    GIS_ID NUMBER PRIMARY KEY,
    MEM_NO NUMBER,  -- 사용자 ID (Primary Key)
    LTITUDE NUMBER(9, 6) NOT NULL,  -- 위도 (NULL 불가)
    LONGITUDE NUMBER(9, 6) NOT NULL, -- 경도 (NULL 불가)
    ADDRESS VARCHAR2(255),          -- 주소 (선택 사항)
    
    CONSTRAINT MGIS_MEMNO_FK FOREIGN KEY(MEM_NO)
    REFERENCES MEMBER(MEM_NO)
);
COMMENT ON COLUMN MEM_GIS.GIS_ID IS '사용자 위치 아이디';
COMMENT ON COLUMN MEM_GIS.MEM_NO IS '사용자 ID';
COMMENT ON COLUMN MEM_GIS.LTITUDE IS '위도';
COMMENT ON COLUMN MEM_GIS.LONGITUDE IS '경도';
COMMENT ON COLUMN MEM_GIS.ADDRESS IS '주소';