DROP TABLE REVIEW_ANSWER;

CREATE TABLE REVIEW_ANSWER
(
    R_ANSWER_NO NUMBER PRIMARY KEY,
    R_ANSWER VARCHAR2(4000) CONSTRAINT R_ANSWER_NN NOT NULL
);
COMMENT ON COLUMN REVIEW_ANSWER.R_ANSWER_NO IS '리뷰에 대한 답글 번호';
COMMENT ON COLUMN REVIEW_ANSWER.R_ANSWER IS '리뷰에 대한 답글';

COMMENT ON COLUMN COMMENTARY.WRITE_NO IS '감상문 번호';